---
- name: Download zip
  get_url:
    url: "{{ ds_versions[ds_version]['url'] }}"
    dest: "{{ ds_home_link }}/downloads/{{ ds_versions[ds_version]['url']|basename }}"
    checksum: "{{ ds_versions[ds_version]['checksum'] }}"
    timeout: 300
    mode: 1373
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
  register: get_url_result
  until: get_url_result is succeeded
