---
- name: Create owner
  user:
    name: "{{ ds_owner }}"
    shell: /bin/bash
    system: true

- name: Create home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    mode: 0755
  with_items:
    - "{{ opends_home }}" 
    - "{{ opends_home}}/downloads"
    - "{{ opends_home }}/{{opends_version}}"
       
- include: download.yml
- include: install.yml
