---
dependencies:
#  - {role: robertdebock.bootstrap,  tags: ansible }
  - {role: bootstrap,               tags: ansible }
  - {role: lcm,                     tags: ansible }
  - {role: lvm,                     tags: lvm }
  - {role: ansible-apt,             tags: apt, when: ansible_os_family == 'Debian' }
  - {role: ajsalminen.hosts,        tags: network }
#  - {role: ansible-hostname,        tags: hostname }
  - {role: Stouts.sudo,             tags: sudo }
  - {role: knopki.locale,           tags: locale }
#  - {role: manala.motd,             tags: motd }
  - {role: alias,                   tags: alias }
  - {role: marcelnijenhof.firewalld,tags: network, when: ansible_os_family == 'RedHat' }
  - {role: c2platform.platform.monit, tags: monitoring }
  - {role: c2platform.test.swid, tags: swid }
  - {role: cacerts, tags: ssl }
